const readingIncluded = [
  { title: "Personalised interpretation", body: "Guidance shaped around the intention and service you selected." },
  { title: "Relevant influences", body: "Space to explore the energies and themes connected with your question." },
  { title: "Clear guidance", body: "A reflective session to help you understand your next step." },
];

const healingIncluded = [
  { title: "Focused energy work", body: "A healing journey held around the focus of the selected offering." },
  { title: "Remote practice", body: "The healing is carried out remotely across the stated duration." },
  { title: "Integration space", body: "Time to notice and reflect on your experience after the work." },
];

const spellworkIncluded = [
  { title: "Purposeful intention", body: "A personalised spellwork offering built around your stated intention." },
  { title: "Energetic support", body: "Focused spiritual intention work for positive movement and clarity." },
  { title: "Guided follow-through", body: "Practical and energetic guidance to support your next step." },
];

const guidanceIncluded = [
  { title: "Live 1:1 guidance", body: "An intuitive conversation shaped around your exact intention." },
  { title: "Clarity and alignment", body: "A grounded session focused on insight, patterns and grounded next steps." },
  { title: "Session recap", body: "Written notes and reflection points to revisit after the call." },
];

const readingFaqs = [
  { q: "How should I prepare for my reading?", a: "Come with an open mind and, if you'd like, a specific question or area of life you want clarity on. There's nothing you need to bring beyond that — I'll guide the flow of the session." },
  { q: "Is this session confidential?", a: "Yes, completely. Every conversation is held in strict confidence — this is a safe, judgment-free space." },
  { q: "Can international clients book?", a: "Absolutely — sessions are available worldwide. Time slots are shown automatically in your local time zone at booking." },
];

const healingFaqs = [
  { q: "What does an energy healing session feel like?", a: "Most clients describe a sense of lightness, calm, or emotional release. Sensations vary from person to person." },
  { q: "Do I need to do anything during the session?", a: "Just find a quiet, comfortable space. I'll guide you through everything else." },
  { q: "Is this a substitute for medical or mental health treatment?", a: "No. This is a complementary spiritual practice, not a replacement for medical or psychological care." },
];

const spellworkFaqs = [
  { q: "What is intentional spellwork?", a: "Spellwork is focused spiritual intention work created around a specific desired area of life. It supports energetic focus and positive movement and is shaped around your current situation." },
  { q: "Does spellwork guarantee a result?", a: "No. Spellwork is designed to support energetic focus and positive movement, but it does not replace real-world action and it does not override another person's free will." },
  { q: "Can I book a spellwork offering for a specific intention?", a: "Yes. Each working is personalised according to the intention and situation you bring." },
];

const guidanceFaqs = [
  { q: "What kind of questions can I bring?", a: "Anything from a life transition to a general feeling of being lost — this session meets you wherever you are." },
  { q: "Is this a religious or spiritual practice?", a: "It's a spiritual guidance practice rooted in intuition, energy work and soulful reflection — approached with respect for wherever you're coming from." },
  { q: "Can international clients book?", a: "Yes — available worldwide with automatic time-zone conversion." },
];

const tarotQuestions = {
  "general-guidance-reading": [
    "What is my current overall energy?",
    "What is currently influencing my life or situation?",
    "What is the biggest challenge or lesson I am experiencing?",
    "What opportunities are currently opening for me?",
    "What am I not seeing clearly at this time?",
    "What should I focus my energy on right now?",
    "What guidance do I need for my next step?",
  ],
  "love-and-relationship-reading": [
    "What is the current energy of this connection?",
    "What are their current feelings towards me?",
    "What are they currently thinking about me and this connection?",
    "What are they not expressing or communicating?",
    "What is the biggest challenge or blockage between us?",
    "What is influencing the connection at present?",
    "What is the potential direction of this relationship?",
    "What guidance do I need regarding this connection?",
  ],
  "career-and-finance-reading": [
    "What is my current career energy?",
    "What is currently influencing my professional growth?",
    "What is blocking or slowing my career progress?",
    "What opportunities are coming towards me?",
    "Is a job or career change indicated at this time?",
    "What is the current energy around my finances?",
    "What action or direction can support greater career and financial movement?",
    "What guidance do I need for my professional and financial path?",
  ],
  "detailed-life-path-reading": [
    "What is my current overall life energy?",
    "What is my soul currently learning?",
    "What is my deeper life purpose or direction?",
    "What patterns are currently influencing my life?",
    "What is unfolding in my love and relationship life?",
    "What is unfolding in my career and professional life?",
    "What is the current energy around my finances and abundance?",
    "What major challenges or lessons should I be aware of?",
    "What opportunities are opening for me?",
    "What is the overall guidance for my next chapter?",
  ],
  "will-they-come-back": [
    "What is their current energy towards me?",
    "What are they currently thinking about our connection?",
    "What are they currently feeling but not expressing?",
    "What caused or contributed to the current distance?",
    "What is stopping or delaying communication?",
    "Do they currently hold an intention or openness to reconnect?",
    "What is the likely direction of this connection from here?",
    "What do I need to understand and focus on for my own highest good?",
  ],
  "future-spouse-and-marriage-timing": [
    "What is the current energy surrounding my love and marriage path?",
    "What qualities or personality traits may my future spouse have?",
    "What type of connection am I likely to share with my future spouse?",
    "How or where may I meet my future spouse?",
    "Is my marriage energy more aligned with love, arranged or a combination?",
    "What challenges or lessons may arise before marriage?",
    "What is the likely timing and overall energy surrounding marriage?",
  ],
  "the-connection-truth": [
    "What is my energy towards this person?",
    "What is their energy towards me?",
    "What are they consciously thinking about me?",
    "What are they subconsciously feeling?",
    "What are they not expressing or saying?",
    "What do they value, miss or feel drawn towards in this connection?",
    "What is the biggest blockage between us?",
    "What is the deeper purpose or lesson of this connection?",
    "What is likely to unfold next?",
    "What do I need to know or do moving forward?",
  ],
  "karmic-contracts": [
    "Why did this person enter my life?",
    "What is the deeper purpose of this connection?",
    "What karmic or repeating pattern exists between us?",
    "What am I meant to learn from this person?",
    "What are they meant to learn from me or this connection?",
    "What unresolved energy is being activated?",
    "Why does this connection feel particularly significant?",
    "Is this connection meant to continue, transform or complete?",
    "What is the soul-level guidance for me?",
  ],
  "money-block-decoder": [
    "What is my current money energy?",
    "What is my biggest visible financial blockage?",
    "What is the deeper root behind this blockage?",
    "What subconscious belief may be affecting my relationship with money?",
    "Where am I unconsciously limiting myself?",
    "What opportunity or financial possibility am I currently overlooking?",
    "What internal shift or pattern needs attention?",
    "What guidance can support healthier financial flow and receiving?",
  ],
  "the-blockage-behind-the-blockage": [
    "What appears to be blocking me?",
    "What is the actual root of this blockage?",
    "What subconscious pattern is influencing this situation?",
    "What fear or belief is keeping me stuck?",
    "What am I unconsciously repeating?",
    "What needs to be released or understood?",
    "What can help me move beyond this cycle?",
    "What becomes possible once I work through this blockage?",
  ],
};

export const services = [
  {
    slug: "one-question-tarot-reading",
    category: "Tarot & Intuitive Readings",
    type: "tarot",
    name: "1 Question Tarot Reading",
    tagline: "A focused reading for one clear question and the guidance you need around it.",
    price: 399,
    priceLabel: "₹399",
    duration: "45 min",
    questionCount: "1 Question",
    focusAreas: ["One specific concern", "Focused guidance", "Present situation", "Clear next step"],
    description: "A focused reading for clients who have one clear question and want detailed intuitive guidance around it.",
    disclaimer: "Tarot offers reflection and guidance, not fixed predictions. You remain the author of your choices and your path.",
    icon: "tarot",
    included: readingIncluded,
    faqs: readingFaqs,
    questions: ["Your one specific question"],
  },
  {
    slug: "three-question-tarot-reading",
    category: "Tarot & Intuitive Readings",
    type: "tarot",
    name: "3 Question Tarot Reading",
    tagline: "A deeper reading for three specific concerns or connected questions.",
    price: 999,
    priceLabel: "₹999",
    duration: "45 min",
    questionCount: "3 Questions",
    focusAreas: ["Three specific concerns", "Interconnected questions", "Deep clarity", "Overall guidance"],
    description: "A deeper reading for clients who want clarity on three specific questions. Each question is interpreted individually, with the overall message connected at the end.",
    disclaimer: "Tarot offers reflection and guidance, not fixed predictions. You remain the author of your choices and your path.",
    icon: "tarot",
    included: readingIncluded,
    faqs: readingFaqs,
    questions: ["Question 1", "Question 2", "Question 3"],
  },
  {
    slug: "general-guidance-reading",
    category: "Tarot & Intuitive Readings",
    type: "tarot",
    name: "General Guidance Reading",
    tagline: "A complete energy check for understanding what is currently unfolding in your life.",
    price: 1111,
    priceLabel: "₹1,111",
    duration: "45 min",
    questionCount: "7 Key Questions",
    focusAreas: ["Current life energy", "Challenges", "Opportunities", "Direction"],
    description: "A complete energy check for clients who do not have one specific question but want to understand what is currently unfolding in their life.",
    disclaimer: "Tarot offers reflection and guidance, not fixed predictions. You remain the author of your choices and your path.",
    icon: "tarot",
    included: readingIncluded,
    faqs: readingFaqs,
    questions: tarotQuestions["general-guidance-reading"],
  },
  {
    slug: "love-and-relationship-reading",
    category: "Tarot & Intuitive Readings",
    type: "tarot",
    name: "Love & Relationship Reading",
    tagline: "A detailed relationship spread for understanding emotional and energetic dynamics.",
    price: 1299,
    priceLabel: "₹1,299",
    duration: "45 min",
    questionCount: "8 Key Questions",
    focusAreas: ["Love", "Feelings", "Thoughts", "Challenges", "Future Direction"],
    description: "A detailed relationship spread for understanding the emotional and energetic dynamics of a connection.",
    disclaimer: "This reading supports reflection and choice. It cannot guarantee another person's actions or override their free will.",
    icon: "heart",
    included: readingIncluded,
    faqs: readingFaqs,
    questions: tarotQuestions["love-and-relationship-reading"],
  },
  {
    slug: "career-and-finance-reading",
    category: "Tarot & Intuitive Readings",
    type: "tarot",
    name: "Career & Finance Reading",
    tagline: "Clarity around career movement, job decisions, business energy and finances.",
    price: 1299,
    priceLabel: "₹1,299",
    duration: "45 min",
    questionCount: "8 Key Questions",
    focusAreas: ["Career", "Job", "Business", "Money", "Opportunities"],
    description: "A detailed reading for professional growth, job changes, business decisions, financial patterns and upcoming opportunities.",
    disclaimer: "This reading supports reflection and choice. It is not financial, legal or employment advice and cannot guarantee an outcome.",
    icon: "briefcase",
    included: readingIncluded,
    faqs: readingFaqs,
    questions: tarotQuestions["career-and-finance-reading"],
  },
  {
    slug: "detailed-life-path-reading",
    category: "Tarot & Intuitive Readings",
    type: "tarot",
    name: "Detailed Life Path Reading",
    tagline: "An extensive reading covering the major areas of life and the energies shaping your next chapter.",
    price: 2222,
    priceLabel: "₹2,222",
    duration: "60 min",
    questionCount: "10 Key Questions",
    focusAreas: ["Love", "Career", "Finance", "Purpose", "Spiritual Growth"],
    description: "An extensive reading covering the major areas of life and the energies surrounding the client's next chapter.",
    disclaimer: "Tarot offers reflection and guidance, not fixed predictions. You remain the author of your choices and your path.",
    icon: "star",
    included: readingIncluded,
    faqs: readingFaqs,
    questions: tarotQuestions["detailed-life-path-reading"],
  },
  {
    slug: "will-they-come-back",
    category: "Signature Soul Readings",
    type: "tarot",
    name: "Will They Come Back?",
    tagline: "A relationship-focused spread for clarity around separation, distance and reconnection.",
    price: 777,
    priceLabel: "₹777",
    duration: "45 min",
    questionCount: "8 Key Questions",
    focusAreas: ["Reconnection", "Feelings", "Thoughts", "Distance", "Communication"],
    description: "A relationship-focused spread for clients seeking clarity around a separation, distance, no-contact situation or the possibility of reconnection.",
    disclaimer: "This reading supports reflection and choice. It cannot guarantee another person's actions or override their free will.",
    icon: "heart",
    included: readingIncluded,
    faqs: readingFaqs,
    questions: tarotQuestions["will-they-come-back"],
  },
  {
    slug: "future-spouse-and-marriage-timing",
    category: "Signature Soul Readings",
    type: "tarot",
    name: "Future Spouse & Marriage Timing",
    tagline: "A focused future-oriented spread exploring the energy around marriage and a future spouse.",
    price: 777,
    priceLabel: "₹777",
    duration: "45 min",
    questionCount: "7 Key Questions",
    focusAreas: ["Future spouse", "Meeting", "Marriage", "Timing", "Married life"],
    description: "A focused future-oriented spread exploring the energy surrounding marriage and the qualities of a future spouse.",
    disclaimer: "This reading supports reflection and choice. It cannot guarantee another person's actions or override their free will.",
    icon: "star",
    included: readingIncluded,
    faqs: readingFaqs,
    questions: tarotQuestions["future-spouse-and-marriage-timing"],
  },
  {
    slug: "the-connection-truth",
    category: "Signature Soul Readings",
    type: "tarot",
    name: "The Connection Truth",
    tagline: "A deep connection analysis designed to look beneath the surface of the bond.",
    price: 1111,
    priceLabel: "₹1,111",
    duration: "45 min",
    questionCount: "10 Key Questions",
    focusAreas: ["Feelings", "Thoughts", "Unspoken emotions", "Blocks", "Purpose"],
    description: "A deep connection analysis designed to look beneath the surface and explore what is actually influencing the bond.",
    disclaimer: "This reading supports reflection and choice. It cannot guarantee another person's actions or override their free will.",
    icon: "eye",
    included: readingIncluded,
    faqs: readingFaqs,
    questions: tarotQuestions["the-connection-truth"],
  },
  {
    slug: "karmic-contracts",
    category: "Signature Soul Readings",
    type: "tarot",
    name: "Karmic Contracts",
    tagline: "A deeper spiritual spread for significant connections that feel especially intense or transformative.",
    price: 1555,
    priceLabel: "₹1,555",
    duration: "60 min",
    questionCount: "9 Key Questions",
    focusAreas: ["Soul lessons", "Patterns", "Purpose", "Unresolved energy"],
    description: "A deeper spiritual spread for significant connections that feel unusually intense, familiar or transformative.",
    disclaimer: "This reading supports reflection and choice. It cannot guarantee another person's actions or override their free will.",
    icon: "key",
    included: readingIncluded,
    faqs: readingFaqs,
    questions: tarotQuestions["karmic-contracts"],
  },
  {
    slug: "money-block-decoder",
    category: "Signature Soul Readings",
    type: "tarot",
    name: "Money Block Decoder",
    tagline: "A specialised spread for understanding the patterns influencing your relationship with money.",
    price: 1111,
    priceLabel: "₹1,111",
    duration: "45 min",
    questionCount: "8 Key Questions",
    focusAreas: ["Money energy", "Blocks", "Beliefs", "Opportunities"],
    description: "A specialised spread exploring the emotional, mental and energetic patterns influencing the client's relationship with money.",
    disclaimer: "This reading supports reflection and choice. It is not financial, legal or employment advice and cannot guarantee an outcome.",
    icon: "briefcase",
    included: readingIncluded,
    faqs: readingFaqs,
    questions: tarotQuestions["money-block-decoder"],
  },
  {
    slug: "the-blockage-behind-the-blockage",
    category: "Signature Soul Readings",
    type: "tarot",
    name: "The Blockage Behind the Blockage",
    tagline: "A root-level spread for clients who know something is not moving but cannot identify why.",
    price: 1111,
    priceLabel: "₹1,111",
    duration: "45 min",
    questionCount: "8 Key Questions",
    focusAreas: ["Root cause", "Subconscious patterns", "Fear", "Repetition"],
    description: "A root-level spread for clients who know something is not moving but cannot identify why.",
    disclaimer: "This reading supports reflection and choice. It cannot guarantee another person's actions or override their free will.",
    icon: "sparkles",
    included: readingIncluded,
    faqs: readingFaqs,
    questions: tarotQuestions["the-blockage-behind-the-blockage"],
  },
  {
    slug: "lunar-release",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Lunar Release",
    tagline: "A 3-Day healing for emotional release, letting go and inner peace.",
    price: 2222,
    priceLabel: "₹2,222",
    duration: "3-Day",
    focusAreas: ["Emotional release", "Letting go", "Inner peace", "Closure"],
    description: "Designed for periods of emotional heaviness, overthinking, attachment to the past or difficulty moving forward.",
    focusesOn: "Releasing emotional weight, reducing attachment to repetitive thoughts, creating space for inner calm and supporting healthier emotional detachment.",
    suitableFor: "Breakups, emotional overwhelm, difficult memories, unresolved feelings, repeated overthinking and situations where the client feels emotionally stuck.",
    intendedShift: "From emotional heaviness and repetitive thinking towards greater calm, acceptance, clarity and emotional space.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "moon",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "mirror-reclaim",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Mirror Reclaim",
    tagline: "A 3-Day healing centred on self-worth, confidence and personal power.",
    price: 2222,
    priceLabel: "₹2,222",
    duration: "3-Day",
    focusAreas: ["Self-worth", "Confidence", "Boundaries", "Personal power"],
    description: "Designed when a person has begun questioning their value, confidence or identity because of a relationship or difficult life experience.",
    focusesOn: "Self-worth, confidence, emotional independence, personal boundaries and reconnecting with one's own identity.",
    suitableFor: "Validation-seeking, relationship insecurity, comparison, feeling ignored or undervalued, emotional dependency and losing oneself in a connection.",
    intendedShift: "From self-doubt and external validation towards stronger self-recognition, confidence and personal power.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "eye",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "cord-unbound",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Cord Unbound",
    tagline: "A 3-Day healing for attachment, detachment and emotional freedom.",
    price: 2222,
    priceLabel: "₹2,222",
    duration: "3-Day",
    focusAreas: ["Attachment", "Detachment", "Closure", "Emotional freedom"],
    description: "Designed for intense emotional attachment to a person, relationship or past situation.",
    focusesOn: "Healthy energetic distance, emotional closure, releasing repetitive attachment patterns and redirecting attention back to the self.",
    suitableFor: "Difficulty moving on, constant thoughts about someone, past relationship attachment, emotional dependency and unresolved connections.",
    intendedShift: "From unhealthy emotional fixation towards healthier detachment, self-reconnection and emotional freedom.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "key",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "unspoken",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Unspoken",
    tagline: "A 3-Day healing for communication, expression and emotional clarity.",
    price: 2222,
    priceLabel: "₹2,222",
    duration: "3-Day",
    focusAreas: ["Communication", "Expression", "Emotional clarity", "Understanding"],
    description: "Designed for situations where emotions remain unexpressed or communication feels blocked.",
    focusesOn: "The client's own relationship with expression, emotional clarity, honesty, communication and boundaries.",
    suitableFor: "No-contact situations, communication gaps, fear of expressing emotions, misunderstandings and things left unsaid.",
    intendedShift: "From emotional suppression and confusion towards clearer expression and healthier communication.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "heart",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "aura-veil",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Aura Veil",
    tagline: "A 3-Day healing designed as an energetic reset and protection ritual.",
    price: 2555,
    priceLabel: "₹2,555",
    duration: "3-Day",
    focusAreas: ["Cleansing", "Protection", "Boundaries", "Renewal"],
    description: "Designed as an energetic reset for periods of heaviness, exhaustion or feeling affected by external environments.",
    focusesOn: "Energetic cleansing, personal boundaries, renewal and restoring a stronger sense of energetic balance.",
    suitableFor: "Feeling drained after interactions, emotional heaviness, stressful environments, overwhelm and a desire for an energetic reset.",
    intendedShift: "From heaviness and energetic exhaustion towards a greater sense of balance, clarity and protection.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "sparkles",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "rose-rebirth",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Rose Rebirth",
    tagline: "A 5-Day healing for heartbreak, emotional healing and self-love.",
    price: 3333,
    priceLabel: "₹3,333",
    duration: "5-Day",
    focusAreas: ["Heartbreak", "Emotional healing", "Self-love", "New beginnings"],
    description: "Designed for deeper emotional recovery after heartbreak, rejection or painful relationship experiences.",
    focusesOn: "Emotional release, self-love, processing disappointment, forgiveness, heart-centred renewal and openness to healthier future experiences.",
    suitableFor: "Breakups, rejection, betrayal, emotional exhaustion, resentment and fear of opening the heart again.",
    intendedShift: "From emotional pain and guardedness towards self-love, emotional restoration and readiness for a new chapter.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "lotus",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "ember-restoration",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Ember Restoration",
    tagline: "A 5-Day healing for passion, vitality and emotional warmth.",
    price: 3333,
    priceLabel: "₹3,333",
    duration: "5-Day",
    focusAreas: ["Passion", "Vitality", "Emotional warmth", "Connection"],
    description: "Designed when life or a relationship feels emotionally flat, disconnected or lacking warmth.",
    focusesOn: "Personal vitality, emotional openness, warmth, enthusiasm and the client's own capacity to connect.",
    suitableFor: "Emotional distance, loss of excitement, relationship routine, low personal energy and feeling disconnected from joy.",
    intendedShift: "From emotional dullness towards renewed vitality, warmth and openness to connection.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "flame",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "venus-renewal",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Venus Renewal",
    tagline: "A 5-Day healing to reconnect with self-love, confidence and receptivity.",
    price: 3333,
    priceLabel: "₹3,333",
    duration: "5-Day",
    focusAreas: ["Love", "Self-love", "Receptivity", "Feminine energy"],
    description: "Designed to reconnect the client with self-love, confidence, receptivity and a healthier relationship with love.",
    focusesOn: "Self-value, emotional receptivity, confidence, healthy attraction and becoming more comfortable receiving affection and appreciation.",
    suitableFor: "Feeling undeserving of love, difficulty receiving, relationship disappointments, low romantic confidence and disconnection from one's feminine energy.",
    intendedShift: "From guardedness and unworthiness towards self-love, receptivity and emotional confidence.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "heart",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "crown-awakening",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Crown Awakening",
    tagline: "A 5-Day healing for confidence, visibility and personal power.",
    price: 3333,
    priceLabel: "₹3,333",
    duration: "5-Day",
    focusAreas: ["Confidence", "Visibility", "Recognition", "Personal power"],
    description: "Designed for clients who feel overlooked, undervalued or hesitant to step into their potential.",
    focusesOn: "Self-belief, healthy visibility, leadership energy, self-expression and recognition of personal capabilities.",
    suitableFor: "Career insecurity, fear of judgement, difficulty speaking up, feeling unseen and lack of confidence.",
    intendedShift: "From hesitation and self-doubt towards stronger confidence, visibility and personal authority.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "star",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "golden-current",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Golden Current",
    tagline: "A 5-Day healing surrounding abundance, prosperity and receiving.",
    price: 3333,
    priceLabel: "₹3,333",
    duration: "5-Day",
    focusAreas: ["Abundance", "Prosperity", "Receiving", "Opportunity"],
    description: "Designed around the client's relationship with abundance, receiving and financial possibility.",
    focusesOn: "Scarcity patterns, limiting beliefs around receiving, openness to opportunities and a healthier internal relationship with prosperity.",
    suitableFor: "Fear around money, difficulty receiving, scarcity thinking, repeated financial limitations and feeling disconnected from opportunity.",
    intendedShift: "From scarcity and resistance towards greater receptivity, confidence and conscious abundance.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "sun",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "doorway-clearing",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Doorway Clearing",
    tagline: "A 5-Day healing for stagnation, movement and opportunity.",
    price: 3333,
    priceLabel: "₹3,333",
    duration: "5-Day",
    focusAreas: ["Stagnation", "Movement", "Opportunities", "Clarity"],
    description: "Designed for periods where a person feels stuck despite effort and wants to create space for movement.",
    focusesOn: "Perceived energetic stagnation, clarity, opportunity, decision-making, career movement and readiness for new possibilities.",
    suitableFor: "Repeated delays, career stagnation, lack of opportunities, uncertainty and major transition periods.",
    intendedShift: "From feeling blocked or stagnant towards greater clarity, movement and openness to possibilities.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "key",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "ancestral-release",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Ancestral Release",
    tagline: "A 7-Day deep healing for family patterns, emotional cycles and renewal.",
    price: 4444,
    priceLabel: "₹4,444",
    duration: "7-Day Deep Healing",
    focusAreas: ["Family patterns", "Emotional cycles", "Release", "Renewal"],
    description: "Designed to explore and release awareness around recurring family and generational emotional patterns.",
    focusesOn: "Recognising repeated patterns, emotional conditioning, boundaries, conscious choice and creating healthier patterns moving forward.",
    suitableFor: "Recurring family dynamics, repeating relationship patterns, scarcity patterns and emotional behaviours that seem to repeat across generations.",
    intendedShift: "From unconscious repetition towards awareness, healthier boundaries and more conscious choices.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "moon",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "beyond-the-veil",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Beyond the Veil",
    tagline: "A 7-Day deep healing for transitions, relocation and new paths.",
    price: 4444,
    priceLabel: "₹4,444",
    duration: "7-Day Deep Healing",
    focusAreas: ["Transitions", "Relocation", "New paths", "Adaptation"],
    description: "Designed for major life transitions including relocation, moving abroad, changing environments or entering a new chapter.",
    focusesOn: "Emotional preparation, stability during change, alignment with a new chapter, confidence and releasing fear of the unknown.",
    suitableFor: "Relocation, international moves, new jobs, major life changes and leaving an old environment behind.",
    intendedShift: "From uncertainty around change towards greater emotional stability, clarity and readiness for transition.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "eye",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "destiny-reset",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Destiny Reset",
    tagline: "A 7-Day deep healing for alignment, direction and clarity.",
    price: 4444,
    priceLabel: "₹4,444",
    duration: "7-Day Deep Healing",
    focusAreas: ["Alignment", "Direction", "Clarity", "Opportunity"],
    description: "Designed for people who feel directionless, stagnant or disconnected from where their life is heading.",
    focusesOn: "Clarity, renewed intention, personal alignment, decision-making and receptivity to opportunities.",
    suitableFor: "Career uncertainty, major life decisions, repeated stagnation, feeling misaligned and entering a new chapter.",
    intendedShift: "From confusion and stagnation towards clearer direction, renewed intention and forward movement.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "sun",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "rebirth-code",
    category: "SoulMirror Healings",
    type: "healing",
    name: "Rebirth Code",
    tagline: "An 11-Day deep transformation for release, identity and renewal.",
    price: 6666,
    priceLabel: "₹6,666",
    duration: "11-Day Deep Transformation",
    focusAreas: ["Transformation", "Release", "Identity", "Renewal", "Alignment"],
    description: "The most intensive SoulMirror healing journey, designed for clients who feel ready for a deeper personal reset and transition into a new chapter.",
    focusesOn: "Progressive emotional release, outdated patterns, identity renewal, self-reconnection, alignment and conscious transformation.",
    suitableFor: "Major life transitions, repeated emotional cycles, deep personal change, identity shifts and closing one chapter while preparing for another.",
    intendedShift: "From an outdated emotional or energetic pattern towards renewal, self-reconnection and a consciously chosen new chapter.",
    disclaimer: "Healing is a complementary spiritual practice and does not replace medical or psychological care or guarantee a specific outcome.",
    icon: "sparkles",
    included: healingIncluded,
    faqs: healingFaqs,
    questions: [],
  },
  {
    slug: "love-attraction-and-sweetening",
    category: "Intentional Spellwork",
    type: "spellwork",
    name: "Love Attraction & Sweetening",
    tagline: "A 3-Day spellwork for romantic warmth, affection and emotional openness.",
    price: 1888,
    priceLabel: "₹1,888",
    duration: "3-Day",
    focusAreas: ["Attraction", "Warmth", "Affection", "Emotional openness"],
    description: "Designed for clients who want to cultivate a warmer romantic energy around their love life or an existing connection.",
    focusesOn: "Romantic warmth, affection, emotional openness, positive attention and a softer relationship atmosphere.",
    bestSuitedFor: "New attraction intentions, existing connections that feel emotionally cold, desire for more warmth and romantic openness.",
    intendedMovement: "To support an atmosphere of attraction, warmth and emotional receptivity while respecting free will.",
    disclaimer: "Spellwork does not guarantee a specific outcome, replace real-world action or override another person's free will.",
    icon: "flame",
    included: spellworkIncluded,
    faqs: spellworkFaqs,
    questions: [],
  },
  {
    slug: "reconciliation",
    category: "Intentional Spellwork",
    type: "spellwork",
    name: "Reconciliation",
    tagline: "A 3-Day spellwork for healing, understanding and reconnection.",
    price: 1888,
    priceLabel: "₹1,888",
    duration: "3-Day",
    focusAreas: ["Healing", "Understanding", "Reconnection", "Openness"],
    description: "Designed for situations involving separation, misunderstandings, distance or a desire for peaceful reconnection.",
    focusesOn: "Healing of emotional tension, openness, forgiveness, understanding and the possibility of healthy reconnection.",
    bestSuitedFor: "Breakups, arguments, misunderstandings, emotional distance and relationships where both parties may benefit from a calmer energy.",
    intendedMovement: "To support the possibility of peaceful reconnection without attempting to force another person's decision.",
    disclaimer: "Spellwork does not guarantee a specific outcome, replace real-world action or override another person's free will.",
    icon: "moon",
    included: spellworkIncluded,
    faqs: spellworkFaqs,
    questions: [],
  },
  {
    slug: "communication-and-conversation",
    category: "Intentional Spellwork",
    type: "spellwork",
    name: "Communication & Conversation",
    tagline: "A 3-Day spellwork for expression, openness and understanding.",
    price: 1888,
    priceLabel: "₹1,888",
    duration: "3-Day",
    focusAreas: ["Expression", "Openness", "Contact", "Understanding"],
    description: "Designed for situations where communication feels delayed, distant or blocked.",
    focusesOn: "Openness to communication, emotional expression, conversation and mutual understanding.",
    bestSuitedFor: "No-contact situations, delayed conversations, unresolved matters and things left unsaid.",
    intendedMovement: "To support an energetic environment more receptive to honest and positive communication.",
    disclaimer: "Spellwork does not guarantee a specific outcome, replace real-world action or override another person's free will.",
    icon: "heart",
    included: spellworkIncluded,
    faqs: spellworkFaqs,
    questions: [],
  },
  {
    slug: "job-and-career-attraction",
    category: "Intentional Spellwork",
    type: "spellwork",
    name: "Job & Career Attraction",
    tagline: "A 3-Day spellwork for opportunities, interviews and career movement.",
    price: 1888,
    priceLabel: "₹1,888",
    duration: "3-Day",
    focusAreas: ["Opportunities", "Interviews", "Visibility", "Career movement"],
    description: "Designed around intentions for suitable professional opportunities and forward movement.",
    focusesOn: "Visibility, interviews, professional connections, opportunities and confidence around career movement.",
    bestSuitedFor: "Job searching, career changes, interviews, applications and professional transitions.",
    intendedMovement: "To support focused intention toward suitable opportunities while encouraging the client to take practical action.",
    disclaimer: "Spellwork does not guarantee a specific outcome, replace real-world action or override another person's free will.",
    icon: "briefcase",
    included: spellworkIncluded,
    faqs: spellworkFaqs,
    questions: [],
  },
  {
    slug: "success-and-opportunity",
    category: "Intentional Spellwork",
    type: "spellwork",
    name: "Success & Opportunity",
    tagline: "A 3-Day spellwork for success, recognition and open doors.",
    price: 1888,
    priceLabel: "₹1,888",
    duration: "3-Day",
    focusAreas: ["Success", "Recognition", "Visibility", "Open doors"],
    description: "Designed around an important goal, application, project or opportunity where the client wants to support positive movement.",
    focusesOn: "Recognition, visibility, opportunity, confidence and openness to favourable possibilities.",
    bestSuitedFor: "Exams, applications, projects, important decisions, launches and goal-oriented situations.",
    intendedMovement: "To support a focused and receptive energy around the desired goal.",
    disclaimer: "Spellwork does not guarantee a specific outcome, replace real-world action or override another person's free will.",
    icon: "sun",
    included: spellworkIncluded,
    faqs: spellworkFaqs,
    questions: [],
  },
  {
    slug: "blockage-release-and-energy-clearing",
    category: "Intentional Spellwork",
    type: "spellwork",
    name: "Blockage Release & Energy Clearing",
    tagline: "A 3-Day spellwork for stagnation, resistance and forward movement.",
    price: 1888,
    priceLabel: "₹1,888",
    duration: "3-Day",
    focusAreas: ["Stagnation", "Resistance", "Clearing", "Forward movement"],
    description: "Designed when a situation feels repeatedly delayed, heavy or stuck.",
    focusesOn: "Perceived energetic resistance, stagnation, heaviness and creating space for forward movement.",
    bestSuitedFor: "Repeated delays, lack of progress, feeling stuck despite effort and situations where the client wants a fresh energetic start.",
    intendedMovement: "To support clearing, renewed focus and openness to movement.",
    disclaimer: "Spellwork does not guarantee a specific outcome, replace real-world action or override another person's free will.",
    icon: "sparkles",
    included: spellworkIncluded,
    faqs: spellworkFaqs,
    questions: [],
  },
  {
    slug: "protection-and-evil-eye-clearing",
    category: "Intentional Spellwork",
    type: "spellwork",
    name: "Protection & Evil-Eye Clearing",
    tagline: "A 3-Day spellwork for cleansing, protection and personal boundaries.",
    price: 1555,
    priceLabel: "₹1,555",
    duration: "3-Day",
    focusAreas: ["Cleansing", "Protection", "Boundaries", "Renewal"],
    description: "Designed for clients seeking a focused energetic cleansing and protection working.",
    focusesOn: "Cleansing, energetic boundaries, protection and renewal.",
    bestSuitedFor: "Feeling drained, heavy environments, unwanted external energy and a desire to strengthen personal energetic boundaries.",
    intendedMovement: "To support a stronger sense of energetic protection and personal boundaries.",
    disclaimer: "Spellwork does not guarantee a specific outcome, replace real-world action or override another person's free will.",
    icon: "shield",
    included: spellworkIncluded,
    faqs: spellworkFaqs,
    questions: [],
  },
  {
    slug: "commitment-and-relationship-stability",
    category: "Intentional Spellwork",
    type: "spellwork",
    name: "Commitment & Relationship Stability",
    tagline: "A 5-Day spellwork for commitment, stability and emotional security.",
    price: 3333,
    priceLabel: "₹3,333",
    duration: "5-Day",
    focusAreas: ["Commitment", "Stability", "Consistency", "Emotional security"],
    description: "Designed for relationships where the intention is to cultivate greater stability, consistency and emotional security.",
    focusesOn: "Grounded relationship energy, consistency, emotional security, mutual understanding and commitment-oriented intentions.",
    bestSuitedFor: "Uncertain relationships, inconsistent dynamics and couples seeking greater stability.",
    intendedMovement: "To support a more stable and harmonious relationship dynamic while respecting both individuals' agency.",
    disclaimer: "Spellwork does not guarantee a specific outcome, replace real-world action or override another person's free will.",
    icon: "heart",
    included: spellworkIncluded,
    faqs: spellworkFaqs,
    questions: [],
  },
  {
    slug: "third-party-detachment-and-boundary-work",
    category: "Intentional Spellwork",
    type: "spellwork",
    name: "Third-Party Detachment & Boundary Work",
    tagline: "A 5-Day spellwork for boundaries, detachment and relationship protection.",
    price: 3333,
    priceLabel: "₹3,333",
    duration: "5-Day",
    focusAreas: ["Boundaries", "Detachment", "Clarity", "Relationship protection"],
    description: "Designed for complicated relationship situations involving unwanted external interference or unhealthy emotional entanglement.",
    focusesOn: "Healthy boundaries, detachment from unwanted interference, clarity and protection of the client's emotional space.",
    bestSuitedFor: "Complicated dynamics, external interference and situations where stronger boundaries are needed.",
    intendedMovement: "To support healthier boundaries and reduce unhealthy entanglement rather than control another person's choices.",
    disclaimer: "Spellwork does not guarantee a specific outcome, replace real-world action or override another person's free will.",
    icon: "key",
    included: spellworkIncluded,
    faqs: spellworkFaqs,
    questions: [],
  },
  {
    slug: "money-attraction-and-financial-flow",
    category: "Intentional Spellwork",
    type: "spellwork",
    name: "Money Attraction & Financial Flow",
    tagline: "A 5-Day spellwork around money, opportunity and abundance.",
    price: 2888,
    priceLabel: "₹2,888",
    duration: "5-Day",
    focusAreas: ["Money", "Opportunity", "Abundance", "Receiving"],
    description: "Designed around financial opportunity, abundance and improved receptivity to income-related possibilities.",
    focusesOn: "Money intentions, opportunity, receiving, abundance and forward movement in financial matters.",
    bestSuitedFor: "Financial stagnation, new income intentions, business opportunities and a desire to cultivate a more abundant mindset.",
    intendedMovement: "To support focused intention around financial opportunities alongside practical financial action.",
    disclaimer: "Spellwork does not guarantee a specific outcome, replace real-world action or override another person's free will.",
    icon: "sun",
    included: spellworkIncluded,
    faqs: spellworkFaqs,
    questions: [],
  },
  {
    slug: "business-growth-and-client-attraction",
    category: "Intentional Spellwork",
    type: "spellwork",
    name: "Business Growth & Client Attraction",
    tagline: "A 7-Day spellwork for visibility, client attraction and business growth.",
    price: 4444,
    priceLabel: "₹4,444",
    duration: "7-Day",
    focusAreas: ["Visibility", "Clients", "Growth", "Sales", "Opportunities"],
    description: "Designed for business owners and professionals seeking energetic support around visibility, client attraction and business growth.",
    focusesOn: "Visibility, client attraction, sales opportunities, professional connections and expansion.",
    bestSuitedFor: "New businesses, launches, service providers, sales periods, client acquisition and business expansion.",
    intendedMovement: "To support greater openness to clients, opportunities and favourable professional connections while practical business activity continues.",
    disclaimer: "Spellwork does not guarantee a specific outcome, replace real-world action or override another person's free will.",
    icon: "briefcase",
    included: spellworkIncluded,
    faqs: spellworkFaqs,
    questions: [],
  },
  {
    slug: "visa-travel-and-relocation-alignment",
    category: "Intentional Spellwork",
    type: "spellwork",
    name: "Visa / Travel / Relocation Alignment",
    tagline: "A 7-Day spellwork for movement, alignment and transition.",
    price: 4444,
    priceLabel: "₹4,444",
    duration: "7-Day",
    focusAreas: ["Movement", "Alignment", "Opportunities", "Transition"],
    description: "Designed around intentions involving international travel, relocation, moving abroad or visa-related processes.",
    focusesOn: "Movement, transition, alignment, opportunity and emotional steadiness around the process.",
    bestSuitedFor: "Visa applications, relocation plans, international opportunities and major travel transitions.",
    intendedMovement: "To support a smoother energetic experience around the journey while recognising that visa and travel decisions are made by the relevant authorities.",
    disclaimer: "Spellwork does not guarantee a specific outcome, replace real-world action or override another person's free will.",
    icon: "sun",
    included: spellworkIncluded,
    faqs: spellworkFaqs,
    questions: [],
  },
  {
    slug: "manifestation-coaching",
    category: "Soul Guidance & Manifestation",
    type: "guidance",
    name: "Manifestation Coaching",
    tagline: "A personalised session for clients who know what they want but feel stuck between intention and action.",
    price: null,
    priceLabel: "Custom pricing",
    duration: "Custom",
    focusAreas: ["Intention", "Mindset", "Alignment", "Action"],
    description: "A personalised session for clients who know what they want but feel stuck between intention and action.",
    disclaimer: "Manifestation is personal and does not guarantee a specific outcome. Your choices and real-world action remain essential.",
    icon: "sun",
    included: guidanceIncluded,
    faqs: guidanceFaqs,
    questions: [],
  },
  {
    slug: "soul-guidance-session",
    category: "Soul Guidance & Manifestation",
    type: "guidance",
    name: "Soul Guidance Session",
    tagline: "A deeper intuitive conversation for clarity around yourself, your choices and your current life chapter.",
    price: null,
    priceLabel: "Custom pricing",
    duration: "Custom",
    focusAreas: ["Clarity", "Direction", "Self-understanding"],
    description: "A deeper intuitive conversation for clients seeking clarity around themselves, their choices, patterns or current life chapter.",
    disclaimer: "Guidance is offered for reflection and support. It does not replace professional medical, legal or financial advice.",
    icon: "lotus",
    included: guidanceIncluded,
    faqs: guidanceFaqs,
    questions: [],
  },
  {
    slug: "personalised-manifestation-and-alignment",
    category: "Soul Guidance & Manifestation",
    type: "guidance",
    name: "Personalised Manifestation & Alignment",
    tagline: "A personalised session built around one important goal, transition or intention.",
    price: null,
    priceLabel: "Custom pricing",
    duration: "Custom",
    focusAreas: ["Goals", "Alignment", "Receiving", "Conscious action"],
    description: "A personalised session built around one important goal, transition or intention and designed to identify what may support greater internal alignment and focused action.",
    disclaimer: "Guidance supports reflection and does not guarantee a specific outcome or replace professional advice.",
    icon: "star",
    included: guidanceIncluded,
    faqs: guidanceFaqs,
    questions: [],
  },
  {
    slug: "custom-soulmirror-session",
    category: "Soul Guidance & Manifestation",
    type: "guidance",
    name: "Custom SoulMirror Session",
    tagline: "A fully personalised session shaped around your specific intention and circumstances.",
    price: null,
    priceLabel: "Custom pricing",
    duration: "Custom",
    focusAreas: ["Fully personalised"],
    description: "For situations that do not fit into a predefined service. The session is created around the client's specific intention, circumstances and desired area of guidance.",
    disclaimer: "Guidance supports reflection and does not guarantee a specific outcome or replace professional advice.",
    icon: "custom",
    included: guidanceIncluded,
    faqs: guidanceFaqs,
    questions: [],
  },
];

const serviceImageBySlug = {
  "one-question-tarot-reading": "tarot_reading_service.png",
  "three-question-tarot-reading": "tarot_reading_service.png",
  "general-guidance-reading": "general_guidance_session_service.png",
  "love-and-relationship-reading": "love_relationship_guidance_service.png",
  "career-and-finance-reading": "career_finance_reading_service.png",
  "detailed-life-path-reading": "detailed_life_path_service.png",
  "will-they-come-back": "connection_truth_service.png",
  "future-spouse-and-marriage-timing": "future_spouse_marriage_service.png",
  "the-connection-truth": "connection_truth_service.png",
  "karmic-contracts": "karmic_contracts_service.png",
  "money-block-decoder": "money_blocker_service.png",
  "the-blockage-behind-the-blockage": "blockage_behind_blockage_service.png",
  "lunar-release": "lunar_release_service.png",
  "mirror-reclaim": "mirror_reclaim_service.png",
  "cord-unbound": "cord_unbound_service.png",
  "unspoken": "unspoken_service.png",
  "aura-veil": "aura_veil_service.png",
  "rose-rebirth": "rose_rebirth_service.png",
  "ember-restoration": "ember_restoration_service.png",
  "venus-renewal": "venus_renewal_service.png",
  "crown-awakening": "crown_awakening_service.png",
  "golden-current": "golden_current_service.png",
  "doorway-clearing": "doorway_cleaning_service.png",
  "ancestral-release": "ancestral_release_service.png",
  "beyond-the-veil": "beyond_veil_service.png",
  "destiny-reset": "destiny_reset_service.png",
  "rebirth-code": "rebirth_code_service.png",
  "love-attraction-and-sweetening": "love_relationship_guidance_service.png",
  "reconciliation": "connection_truth_service.png",
  "communication-and-conversation": "unspoken_service.png",
  "job-and-career-attraction": "career_finance_reading_service.png",
  "success-and-opportunity": "golden_current_service.png",
  "blockage-release-and-energy-clearing": "blockage_behind_blockage_service.png",
  "protection-and-evil-eye-clearing": "aura_veil_service.png",
  "commitment-and-relationship-stability": "crown_awakening_service.png",
  "third-party-detachment-and-boundary-work": "cord_unbound_service.png",
  "money-attraction-and-financial-flow": "money_blocker_service.png",
  "business-growth-and-client-attraction": "manifestation_coaching_service.png",
  "visa-travel-and-relocation-alignment": "doorway_cleaning_service.png",
  "manifestation-coaching": "manifestation_coaching_service.png",
  "soul-guidance-session": "soul_guidance_service.png",
  "personalised-manifestation-and-alignment": "general_guidance_session_service.png",
  "custom-soulmirror-session": "custom_soulmirror_session_service.png",
};

services.forEach((service) => {
  const imageName = serviceImageBySlug[service.slug];
  if (!imageName) return;

  const imageBase = imageName.replace("_service.png", "");
  service.lightImage = `/images/${imageName}`;
  service.darkImage = `/images/${imageBase}_dark_service.png`;
  service.imageAlt = `${service.name} service artwork`;
});

export const testimonials = [
  { name: "Riya M.", tag: "Tarot Reading", quote: "Janvi held space for me without ever making me feel judged. What she reflected back was exactly what I needed to hear." },
  { name: "Aditya K.", tag: "Tarot Reading", quote: "I walked in confused about a career decision and walked out with real clarity, not just comfort." },
  { name: "Simran K.", tag: "Energy Healing", quote: "The energy healing session was unlike anything I'd tried before — I genuinely felt lighter by the end of it." },
  { name: "Neha P.", tag: "Soul Guidance", quote: "She doesn't tell you what you want to hear. She helps you see what's actually true, gently." },
  { name: "David R., UK", tag: "Tarot Reading", quote: "Booking as an international client was seamless — the time-zone conversion just worked, and the session felt deeply personal." },
  { name: "Priya S.", tag: "Manifestation Coaching", quote: "The manifestation coaching gave me an actual framework, not vague affirmations. I've already seen shifts in three weeks." },
];

export const serviceCategories = [
  {
    slug: "tarot-reading",
    name: "Tarot Reading",
    description: "All Tarot & Intuitive Readings + all Signature Soul Readings.",
    services: services.filter((service) => service.category === "Tarot & Intuitive Readings" || service.category === "Signature Soul Readings"),
  },
  {
    slug: "energy-healing",
    name: "Energy Healing",
    description: "All 3-Day, 5-Day, 7-Day and 11-Day SoulMirror Healings.",
    services: services.filter((service) => service.category === "SoulMirror Healings"),
  },
  {
    slug: "intentional-spellwork",
    name: "Intentional Spellwork",
    description: "All 3-Day, 5-Day and 7-Day Intentional Spellwork.",
    services: services.filter((service) => service.category === "Intentional Spellwork"),
  },
  {
    slug: "soul-guidance",
    name: "Soul Guidance",
    description: "Manifestation Coaching, Soul Guidance Session, Personalised Manifestation & Alignment, etc.",
    services: services.filter((service) => service.category === "Soul Guidance & Manifestation"),
  },
];
